---
- name: Install
  ansible.builtin.package:
    name:
      - k9s
    state: latest

- name: skin.yml
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/k9s/skin.yml"
    src: "skin.yml" 
