---
- name: Install
  community.general.snap:
    name: "{{ jetbrains_item }}"
    classic: yes
  become: yes
  loop_control:
    loop_var: jetbrains_item
  with_items:
    - datagrip
    - goland
    - pycharm-professional
    - rider
    - webstorm
