---
- name: Dependencies
  ansible.builtin.package:
    name:
      - base-devel
      - cmake
      - curl
      - ninja
      - tree-sitter
      - unzip
    state: latest

- name: Clone
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir }}/Development/repository/github.com/neovim/neovim"
    repo: git@github.com:neovim/neovim.git
    single_branch: yes
    update: yes
    version: master
  register: clone

- name: Build
  make:
    chdir: "{{ ansible_user_dir }}/Development/repository/github.com/neovim/neovim"
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
  register: build
  when: clone.changed

- name: Install
  make:
    chdir: "{{ ansible_user_dir }}/Development/repository/github.com/neovim/neovim"
    target: install
  become: yes
  when: build.changed

- name: Link init.lua
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/Development/repository/github.com/ALT-F4-LLC/dotfiles/nvim/init.lua"
    dest: "{{ ansible_user_dir }}/.config/nvim/init.lua"
    state: link

- name: Link modules
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/Development/repository/github.com/ALT-F4-LLC/dotfiles/nvim/lua"
    dest: "{{ ansible_user_dir }}/.config/nvim/lua"
    state: link
