---
- name: Install
  ansible.builtin.package:
    name:
      - zsh
    state: latest
  become: yes

- name: Set default
  user:
    name: "{{ ansible_env['USER'] }}"
    shell: /usr/bin/zsh
  become: yes
