---
- name: Install
  ansible.builtin.package:
    name:
      - docker
      - docker-compose
    state: latest
  become: yes

- name: Enable service
  ansible.builtin.systemd:
    enabled: yes
    name: docker
    state: started
  become: yes

- name: Add to group
  ansible.builtin.user:
    append: yes
    groups: docker
    name: "{{ ansible_env['USER'] }}"
  become: yes

- name: Copy daemon.json
  ansible.builtin.template:
    dest: "/etc/docker/daemon.json"
    src: "daemon.json"
  become: yes
  notify: restart_docker
